# Ant properties file for the pipeline which creates documentation and syntax representations
# ${...} references get expanded.

# ucmism2t folder
ucmism2t_dir        = /home/wackerow/TEST/ucmism2t
#ucmism2t_dir        = /media/wackerow/shared/git/github/ucmism2t

# model xmi file eclipse variant
model_file_eclipse  = ${ucmism2t_dir}/example/model/ddi-cdi_canonical-unique-names-eclipse.xmi

# model xmi file
model_file          = ${ucmism2t_dir}/example/model/ddi-cdi_canonical-unique-names.xmi

# file with model-specific properties
model_properties    = ${ucmism2t_dir}/example/model/ddi-cdi_canonical-unique-names-eclipse.properties

# file with generic ucmism2t properties
generic_properties  = ${ucmism2t_dir}/property/generic.properties

# execution binary
launcher            = ${ucmism2t_dir}/releng/ucmism2t.product/target/products/ucmism2t.product/linux/gtk/x86_64/ucmism2t

# folder with generated artefacts
generated_folder    = ${ucmism2t_dir}/generated

# folder for sphinx logs
log_folder          = ${ucmism2t_dir}/log

# Software
software_home=/home/wackerow/software

# Saxon jar
saxon_jar=${software_home}/saxon/SaxonHE12-9J/saxon-he-12.9.jar

# planuml jar
# needed? plantuml_jar=${software_home}/plantuml/plantuml-asl-1.2026.6.jar
