# Ant properties file for the pipeline which creates documentation and syntax representations
# ${...} references get expanded by Ant.

# ucmism2t folder
ucmism2t_dir        = /home/wackerow/TEST2/ucmism2t
#ucmism2t_dir        = /media/wackerow/shared/git/github/ucmism2t

# file with generic ucmism2t properties
generic_properties  = ${ucmism2t_dir}/property/generic.properties

# execution binary
launcher            = ${ucmism2t_dir}/releng/ucmism2t.product/target/products/ucmism2t.product/linux/gtk/x86_64/ucmism2t

# model folder
model_folder        = /media/wackerow/Shared/CDIF/Documentation/Technical/Work/markdown2uml/claude_xmi_40_newStructure
# model_folder        = /media/wackerow/Shared/CDIF/Documentation/Technical/Work/markdown2uml/claude_xmi_39_after_reports
# model_folder        = /media/wackerow/Shared/CDIF/Documentation/Technical/Work/markdown2uml/claude_xmi_38_after_ucmism2t_analysis_2
# model_folder        = /media/wackerow/Shared/CDIF/Documentation/Technical/Work/markdown2uml/claude_xmi_37_after_ucmism2t_analysis
# model_folder        = /media/wackerow/Shared/CDIF/Documentation/Technical/Work/markdown2uml/claude_xmi_36_inheritance_datatype_model_2fixes
# model_folder        = /media/wackerow/Shared/CDIF/Documentation/Technical/Work/markdown2uml/claude_xmi_35_associationNamesFixed
# model_folder        = /media/wackerow/Shared/CDIF/Documentation/Technical/Work/markdown2uml/claude_xmi_34_curiesInAttributeNamesFixed
# model_folder        = /media/wackerow/Shared/CDIF/Documentation/Technical/Work/markdown2uml/claude_xmi_33_curiesInAttributeNames
# model_folder        = /media/wackerow/Shared/CDIF/Documentation/Technical/Work/markdown2uml/claude_xmi_30
# model_folder        = /media/wackerow/Shared/CDIF/Documentation/Technical/Work/markdown2uml/claude_xmi_32_noColonInNames

# folder with generated artefacts
generated_folder    = ${model_folder}/generated

# folder for sphinx logs
log_folder          = ${model_folder}/log

# Software
software_home       = /home/wackerow/software

# Saxon jar. used by XSLT
saxon_jar           = ${software_home}/saxon/SaxonHE12-9J/saxon-he-12.9.jar

# Plantuml jar, used by Sphinx
plantuml_jar        = ${software_home}/plantuml/plantuml-1.2025.2.jar

# model xmi file
# used for xmi fragment extraction
model_file          = ${model_folder}/cdif-universe.xmi

# model xmi file eclipse variant. the name must have the same name as the model_file plus the postfix '_eclipse'.
# used for acceleo processing
model_file_eclipse  = ${model_folder}/cdif-universe_eclipse.xmi

# file with model-specific properties
model_properties    = /media/wackerow/Shared/CDIF/Documentation/Technical/Work/markdown2uml/for_ucmism2t/cdif-model.properties

# logo file for the model
logo_file           = /media/wackerow/Shared/CDIF/Documentation/Technical/Work/markdown2uml/for_ucmism2t/cdif640-transparent.png
