# Ant properties file for the pipeline which creates documentation and syntax representations
# ${...} references get expanded by Ant.

# ucmism2t folder
ucmism2t_dir        = /home/wackerow/TEST/ucmism2t
#ucmism2t_dir        = /media/wackerow/shared/git/github/ucmism2t

# file with generic ucmism2t properties
generic_properties  = ${ucmism2t_dir}/property/generic.properties

# execution binary
launcher            = ${ucmism2t_dir}/releng/ucmism2t.product/target/products/ucmism2t.product/linux/gtk/x86_64/ucmism2t

# folder with generated artefacts
generated_folder    = ${ucmism2t_dir}/generated

# folder for sphinx logs
log_folder          = ${ucmism2t_dir}/log

# Saxon jar
saxon_jar=/home/wackerow/software/saxon/SaxonHE12-9J/saxon-he-12.9.jar

# plantuml jar must be specified in pipeline/sphinx/bookTheme/conf.py - plantuml entry

# model xmi file eclipse variant
model_file_eclipse  = ${ucmism2t_dir}/example/model/ddi-cdi_canonical-unique-names-eclipse.xmi

# file with model-specific properties
model_properties    = ${ucmism2t_dir}/example/model/ddi-cdi_canonical-unique-names-eclipse.properties

# model xmi file
model_file          = ${ucmism2t_dir}/example/model/ddi-cdi_canonical-unique-names.xmi

# logo file for the model
logo_file           = ${ucmism2t_dir}/example/logo/cdi.svg