# Retrieve value with ['<key>'.getPropertyValue()/] in mtl files.

# DDI-CDI specific

DDI-CDI = true

# The main package of the model for which encodings and subset documentation should be generated,
# in qualified name syntax.
MAIN_PACKAGE_NAME=DDICDIModels::DDICDILibrary

#doc = true
#jsonld = true
#jsonschema = true
#onto = true
#shacl = true
#shex = true
xsd = true
test = true

# include all items in the generation
includeAllItems = true

# the path of encoding uris is adjusted by javascript function changeUrl in custom.js
XMI_URI = /encoding/xmi/ddi-cdi_canonical-unique-names.xmi
XSD_URI = /encoding/xml-schema/ddi-cdi.xsd
ONTO_URI = /encoding/ontology/ddi-cdi.onto.ttl
JSONLD_URI = /encoding/json-ld/ddi-cdi.jsonld
XSD_NS = http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/
RDF_NS = http://ddialliance.org/Specification/DDI-CDI/1.0/RDF/
RDF_PREFIX = cdi

# for createRedirectHtml but not used 
# DDI-CDI_DOCUMENTATION_ROOT = https://ddi-alliance.bitbucket.io/DDI-CDI/DDI-CDI_2023-05-24/doc/_build/

# comma separated list
# for RDF targets
IGNORE_PACKAGE = XMLSchemaDataTypes
# NOT USED ddi-cdi_packages_ignore = Context, DesignPatterns, XMLSchemaDataTypes
ddi-cdi_ambiguous_assoc_names = correspondsTo, has, hasValueFrom, isDefinedBy, takesSubstantiveValuesFrom, uses

ddi-cdi_packages_ignore2 = Context, DesignPatterns
