# include all items in the generation
includeAllItems = true

MAIN_PACKAGE_NAME   = CDIFModels::CDIFUniverse
MODEL_ACRONYM       = CDIFModels
MODEL_LANGUAGE      = en
MODEL_FILE_NAME     = cdif-universe.xmi
MODEL_MAJOR_VERSION = 1
MODEL_MINOR_VERSION = 1
MODEL_URI           = https://cross-domain-interoperability-framework.github.io/cdifbook/
MODEL_TITLE         = Cross-Domain Interoperability Framework
#MODEL_SUB_TITLE     =

doc = true
jsonld = true
jsonschema = true
onto = true
shacl = true
shex = true
xsd = true

test = true


# has a package 'Profiles' with sub-packages which represent profiles
# UML Dependency is used to define references to items in other packages
profiles = true
profiles_package = CDIFProfiles
universe_package = CDIFUniverse

# DON'T SET THESE PROPERTIES. CURIEs and namespaces are set by Packageinformation in the model.
# RDF_NAMESPACE = 
# RDF_PREFIX = 

COPYRIGHT = (c) 2026 Committee on Data of the International Science Council (CODATA)
