# Build Properties for Core Bundle
#
# This file tells the Eclipse/PDE build which resources to include
# in the compiled bundle JAR file.

# Source folders containing Java code and Acceleo templates
source.. = src/

# Files to include in the binary build (runtime)
bin.includes = META-INF/,\
               .,\
               plugin.xml

# Additional files/folders to include
# The dot (.) means include everything compiled from source.. folders
