# Retrieve value with ['<key>'.getPropertyValue()/] in mtl files.

# emit 'WARNING: ELEMENT HAS NO DOCUMENTATION!' if an element has not documentation.
WARNING_MISSING_DOCUMENTATION = false

# write _diagnostic.txt file
diagnostic = false

# comma separated list with mapping items separated by '>'
uml-map-rdf = \
	String						>	xsd:string							, \
	Boolean						>	xsd:boolean							, \
	Integer						>	xsd:integer							, \
	Real							>	xsd:double							, \
	UnlimitedNatural	>	xsd:nonNegativeInteger	, \
	XsdAnyUri					>	xsd:anyURI							, \
  XsdDate           > xsd:date                , \
  XsdDateTime       > xsd:dateTime            , \
	XsdLanguage				>	xsd:language

rdf-static-namespaces = \
  dc        > http://purl.org/dc/elements/1.1/                    , \
  dcterms   > http://purl.org/dc/terms/                           , \
  geosparql > http://www.opengis.net/ont/geosparql#               , \
  owl       > http://www.w3.org/2002/07/owl#                      , \
  prov      > http://www.w3.org/ns/prov#                          , \
  rdf       > http://www.w3.org/1999/02/22-rdf-syntax-ns#         , \
  rdfs      > http://www.w3.org/2000/01/rdf-schema#               , \
  skos      > http://www.w3.org/2004/02/skos/core#                , \
  ucmis     > http://ddialliance.org/Specification/UCMIS/1.0/RDF/ , \
  xsd       > http://www.w3.org/2001/XMLSchema#

uml-diagram-class-default-color = #EEEEEE
uml-diagram-class-emphasis-color = #FFD700
uml-diagram-package-default-color = #FAFAD2
uml-diagram-inheritance-arrow-color = #D2691E
# uml-diagram-package-emphasis-color = #FFD700 not used
#uml-diagram-class-default-color = #EEEEEE
#uml-diagram-class-emphasis-color = #AED6F1
#uml-diagram-package-default-color = #EBF5FB
#uml-diagram-package-emphasis-color = #AED6F1

# Colors based on https://sashamaps.net/docs/resources/20-colors/, accessibility 99,99%. 

# similar colors
# yellow
diagram.mainItem.color=#ffe119
# black
diagram.mainItem.fontColor=#000000

# orange
diagram.mainItemGeneral.color=#f58231
# white
diagram.mainItemGeneral.fontColor=#ffffff
# orange
diagram.inheritancePath.color=#f58231
# maroon
diagram.otherItem.color=#800000
# white
diagram.otherItem.fontColor=#ffffff

# similar colors
# blue
diagram.mainItemContext.color=#4363d8
# white
diagram.mainItemContext.fontColor=#ffffff
# lavender
diagram.dataTypes.color=#dcbeff
# black
diagram.dataTypes.fontColor=#000000

# similar colors
# grey
diagram.designPattern.color=#a9a9a9
# white
diagram.designPattern.fontColor=#ffffff
# white
diagram.otherStandardItem.color=#ffffff
# black
diagram.otherStandardItem.fontColor=#000000
