var modelUrl = 'https://cross-domain-interoperability-framework.github.io/cdifbook/';
var modelDocumentationUrl = '';
var definition = {
	"CDIF": "",
	"CDIFCodelist": "CDIF profile: Codelist (IG-derived; from <IG guide: Codelist>)",
	"CDIFConceptScheme": "CDIF profile: ConceptScheme (IG-derived; from <IG guide: ConceptScheme>)",
	"CDIFCore": "CDIF profile: Core (IG-derived; from <IG guide: Core>)",
	"CDIFDataDescription": "CDIF profile: DataDescription (IG-derived; from <IG guide: DataDescription>)",
	"CDIFDataStructure": "CDIF profile: DataStructure (IG-derived; from <IG guide: DataStructure>)",
	"CDIFDiscovery": "CDIF profile: Discovery (IG-derived; from <IG guide: Discovery>)",
	"CDIFManifest": "CDIF profile: Manifest (IG-derived; from <IG guide: Manifest>)",
	"CDIFProfiles": "",
	"CDIFProvenance": "CDIF profile: Provenance (IG-derived; from <IG guide: Provenance>)",
	"CDIFUniverse": "",
	"Common": "",
	"DCAT": "",
	"DDICDI": "",
	"DQV": "",
	"SF": "",
	"SKOS": "",
	"SPDX": "",
	"Schema": "",
	"Time": "",
	"XMLSchemaDataTypes": "",
	"AbstractDataSet": "**CDIF** AbstractDataSet - abstract supertype for the cdi:PhysicalDataSet co-types a DataDownload may declare (config: ddi-cdi2cdifDataDescription_mapping.json). PROPOSED, not a confirmed addition - see cdif-authors-questions.md.",
	"AbstractDistribution": "**CDIF** AbstractDistribution - abstract supertype shared by DataDownload and WebAPI (config: ddi-cdi2cdifCore_mapping.json).",
	"AbstractMapping": "**CDIF** AbstractMapping - abstract supertype for the cdif:hasPhysicalMapping family: PhysicalMapping (generic), TextMapping (delimited/fixed-width text), LocatorMapping (locator expression for structured data) (config: ddi-cdi2cdifDataDescription_mapping.json).",
	"Action": "**CDIF** *(not documented)*",
	"AdditionalProperty": "**CDIF** PropertyValue values required to define a soft-typed property with a value.",
	"Agent": "**CDIF** cdi:Agent - abstract supertype shared by Person and Organization (config: ddi-cdi2cdifCore_mapping.json).",
	"AgentInRole": "**CDIF** For more granularity on how a person contributed to a Dataset, use schema:Role. The schema.org documentation does not state that the Role type is an expected data type of author, creator and contributor, but that is addressed in this blog post (http://blog.schema.org/2014/06/introducing-rol ...",
	"AttributeComponent": "**CDIF** Role given to a represented variable in the context of a data structure to qualify observations or provide other supplementary information. Permitted in all three concrete DataStructure subtypes.",
	"CatalogRecord": "**CDIF** This is the class used to provide information about the metadata record itself.",
	"CategoryStatistics": "**CDIF** Statistics for a specific Category of an instance variable within a data set. Maps a **Statistic** value object to a category concept. The Statistic value object represents a single computed value (mean, count, median, etc.), with optional computationBase and typeOfNumericValue.",
	"CdifConceptOrTerm": "**CDIF** a data type that can be an object reference, a schema:DefinedTerm, or a skos:Concept as defined in the cdif ConceptScheme profile.",
	"Concept": "**CDIF** SKOS Concept - properties per the guide's second 'Optional Properties' and 'Required Properties' blocks. NOTE: this class has NO heading of its own anywhere in the Codelist guide; its boundary and name were confirmed by the CDIF authors, not extracted from a marker in the source.",
	"ConceptScheme": "**CDIF** The root object representing the codelist or classification scheme. :choiceConstraints: - Required if absent: ````conditionsOfAccess```` - Required if absent: ````license````",
	"ContactPoint": "**CDIF** Information about how to communicate with a person or organization. CDIF only includes e-mail in its schema.",
	"Contributor": "**CDIF** For more granularity on how an agent contributed to a resource, use schema:Role. The schema.org documentation does not state that the Role type is an expected data type for the contributor property, but that is addressed in this blog post (http://blog.schema.org/2014/06/introducing-role.htm ...",
	"DataCatalog": "**CDIF** An accessible collection of data. The data might be metadata (about other resources) or datasets.",
	"DataDownload": "**CDIF** file-based access to a resource via URL; the DataDownload object provides a link to get the resource content, along with information about the serialization format and conventions used.",
	"DataStructure": "**CDIF** Abstract base for ``cdi:DimensionalDataStructure``, ``cdi:LongDataStructure``, and ``cdi:WideDataStructure``. Instances are always typed as one of those subtypes; this class is never instantiated directly. It carries the common properties listed below; the subtypes constrain which ``DataStr ...",
	"DataStructureComponent": "**CDIF** Abstract base for the role-typed components that make up a ``cdi:DataStructure``. Instances are always typed as one of the concrete subtypes below. Every component binds a ``cdif:RepresentedVariable`` to a role inside the structure.",
	"Dataset": "**CDIF** A Data Description record adds the following properties on the root schema:Dataset class: :choiceConstraints: - Required if absent: ````license```` - Required if absent: ````conditionsOfAccess```` - Required if absent: ````distribution```` - Required if absent: ````url````",
	"DefinedTerm": "**CDIF** *Authoritative definition: [CDIF Core profile](https://github.com/Cross-Domain-Interoperability-Framework/profile-core/blob/reviewRevision202606/CDIFCoreImplementationGuide.md#defined-term).* :choiceConstraints: - Required if absent: ````identifier````, ````termCode```` - Required if absent ...",
	"DescriptorMapping": "**CDIF** One entry in a DescriptorValueDomain's takesValuesFrom array: pairs a descriptor code (cdif:value) with the RepresentedVariable it identifies (cdif:isDefinedBy).",
	"DescriptorValueDomain": "**CDIF** *Authoritative definition: ``_sources/cdifDataType/cdifDescriptorVariable/`` (``$defs/DescriptorValueDomain``).*",
	"DescriptorVariable": "**CDIF** *Authoritative definition: ``_sources/cdifDataType/cdifDescriptorVariable/`` in [metadataBuildingBlocks](https://github.com/Cross-Domain-Interoperability-Framework/metadataBuildingBlocks).*",
	"DimensionComponent": "**CDIF** Role given to a represented variable that acts as a coordinate axis in a multidimensional structure. Used only in ``cdi:DimensionalDataStructure``. Dimensions are typically categorical (codelist-valued) or quantized continuous variables (e.g., time bins). The value domain for the represente ...",
	"DimensionGroup": "**CDIF** A set of dimension components that together address a coordinate position within a ``cdi:DimensionalDataStructure``. Used by structures where multiple dimensions share a notional axis (e.g., a ``time`` group containing year/month/day).",
	"DimensionalDataStructure": "**CDIF** Structure of a multidimensional (\"cube\") dataset, described by dimension, measure and attribute components. Subtype of ``cdi:DataStructure``.",
	"EntryPoint": "**CDIF** Use to document the URL that is the target for invoking an action, or that is the target object of a link relationship.",
	"EnumerationDomain": "**CDIF** A wrapper acting as an extension point to allow a cdif Codelist to be documented as enumerated value domain.",
	"ForeignKey": "**CDIF** A set of represented variables whose values match a primary key in another dataset, expressing a cross-dataset reference.",
	"IdentifierComponent": "**CDIF** Role given to a represented variable that identifies the unit (individual) that is the subject of properties specified in the record. Used in ``cdi:WideDataStructure`` and ``cdi:LongDataStructure``.",
	"InstanceVariable": "**CDIF** *(not documented)*",
	"LinkRole": "**CDIF** This is the type used for links that have an associated semantic conveyed by the linkRelationship.",
	"LocatorMapping": "**CDIF** extends cdif:PhysicalMapping. Locates a variable's value(s) within a structured (hierarchical) dataset such as XML or JSON, via a locator expression (e.g., XPath or JSONPath). DDI-CDI LocatorMapping. Used in place of column-index/text mappings for cdi:StructuredDataSet distributions.",
	"LongDataStructure": "**CDIF** Structure of a long (\"entity-attribute-value\") dataset, described by identifier, measure, attribute, variable-descriptor and variable-value components. Subtype of ``cdi:DataStructure``.",
	"MeasureComponent": "**CDIF** Role given to a represented variable that holds the observed or derived values of the dataset. Permitted in ``cdi:DimensionalDataStructure`` and ``cdi:WideDataStructure``. (In ``cdi:LongDataStructure`` the measured value is carried by ``cdif:VariableValueComponent`` instead.)",
	"MediaObject": "**CDIF** *(not documented)*",
	"MonetaryGrant": "**CDIF** *(not documented)* :choiceConstraints: - Required if absent: ````name````, ````funder```` - Required if absent: ````identifier````, ````funder```` - Required if absent: ````identifier````, ````name````",
	"Organization": "**CDIF** *(not documented)* :choiceConstraints: - Required if absent: ````identifier```` - Required if absent: ````name````",
	"Person": "**CDIF** Object representing a person. :choiceConstraints: - Required if absent: ````identifier```` - Required if absent: ````name````",
	"PhysicalMapping": "**CDIF** Defines implementation-specific properties for the representation of a variable in a dataset. Uses 2026 DDI-CDI update flat per-column mapping structure.",
	"PrimaryKey": "**CDIF** An ordered set of represented variables whose values uniquely identify a record in the dataset. Array order in ``cdif:isComposedOf`` is the key position; no intermediate ComponentPosition wrapper is used.",
	"ProperInterval": "**CDIF** Intervals can be bounded by named ordinal eras (e.g. Jurassic, Tang dynasty, Paleolithic) identified by URI, or by numeric bounds that are time coordinates in a specified reference system (implemented by the TimePosition data type). This implementation is a simplified profile based on the [ ...",
	"PropertyValueSpecification": "**CDIF** Description of the kind of value expected for a parameter value.",
	"QualityMeasurement": "**CDIF** *(not documented)*",
	"QuantitativeValue": "**CDIF** object that specifies a numeric value and units of measure",
	"RepresentedVariable": "**CDIF** A conceptual variable bound to a substantive value domain — *logical* in the sense that it is not tied to a particular physical data type or column position. Components in a DataStructure reference RepresentedVariables to indicate which logical variable plays which role. RepresentedVariable ...",
	"SentinelValueDomain": "**CDIF** value domain specifications are the same except for the @type values cdif:SentinelValueDomain and cdif:SubstantiveValueDomain respectively",
	"SimpleFeature": "**CDIF** *(not documented)*",
	"Statistics": "**CDIF** A named bundle of one or more Statistic value objects for an instance variable, optionally weighted, optionally broken down by Category.",
	"StatisticsCollection": "**CDIF** Groups one or more Statistics nodes for an instance variable. A typical use is a dataset-level collection holding row-count / mean / stddev Statistics for each measured variable.",
	"StructuredDataSet": "**CDIF** DataDownload co-typed as cdi:StructuredDataSet: hierarchical/structured data set (XML, JSON, ...). Per-field mappings are LocatorMapping. PROPOSED - sourced from config, not present in the current Implementation Guides.",
	"SubstantiveValueDomain": "**CDIF** value domain specifications are the same except for the @type values cdif:SentinelValueDomain and cdif:SubstantiveValueDomain respectively",
	"TabularTextDataSet": "**CDIF** DataDownload co-typed as cdi:TabularTextDataSet: delimited or fixed-width text data set (CSV/TSV/fixed-width). Per-field mappings are TextMapping. PROPOSED - sourced from config, not present in the current Implementation Guides.",
	"TextMapping": "**CDIF** Physical mapping for a variable in a delimited or fixed-width text dataset. Extends cdifPhysicalMapping with text-format properties (column width and number formatting).",
	"UnitType": "**CDIF** *Defined inline as part of the CDIF Data Structure Component vocabulary; a ``schema:DefinedTerm``-style structured term used for unit-of-measure values that need machine semantics beyond a free-text label.*",
	"ValueAndConceptDescription": "**CDIF** A Formal description of a set of values.",
	"VariableDescriptorComponent": "**CDIF** Role given to a represented variable that holds codes identifying *which* logical variable a given row in a long-format dataset is recording. Used only in ``cdi:LongDataStructure``.",
	"VariableValueComponent": "**CDIF** Role given to a represented variable that carries the value of whichever logical variable the row's ``VariableDescriptorComponent`` identifies. Used only in ``cdi:LongDataStructure``.",
	"WebAPI": "**CDIF** Provides information to request data through a web accessible service endpoint. This implementation uses the schema.org Action to document url or url template and parameters. At this point, schema is set up for one action-- an HTTP Get that requests data. The url template parameters (in cur ...",
	"WideDataStructure": "**CDIF** Structure of a wide (one-row-per-unit) dataset, described by identifier, measure and attribute components. Each record represents properties of one unit in the population. Subtype of ``cdi:DataStructure``.",
	"AbstractGeometry": "**CDIF** AbstractGeometry - abstract supertype shared by GeoCoordinates and GeoShape (config: ddi-cdi2cdifDiscovery_mapping.json).",
	"Checksum": "**CDIF** *(not documented)*",
	"GeoCoordinates": "**CDIF** A point location specified with latitude and longitude in decimal degrees, using the WGS84 spatial reference system.",
	"GeoShape": "**CDIF** CDIF limits schema:GeoShape to a box or line (schema.org includes other options). Point locations are tuples of <U+007B>latitude east-longitude<U+007D> (y x). (documentation from [Science on Schema.org](https://github.com/ESIPFed/science-on-schema.org/blob/develop/guides/Dataset.md#spatial- ...",
	"Identifier": "**CDIF** A reusable identifier wrapper following the schema.org ``schema:PropertyValue`` pattern. **Union-type policy:** in CDIF profile UML models an attribute typed ``schema:Identifier`` / ``schema:PropertyValue`` is represented as a single attribute of that class. The JSON Schema permits the valu ...",
	"LabeledLink": "**CDIF** *(not documented)*",
	"LanguageTaggedValue": "**CDIF** An RDF literal with a language tag, serialized as a JSON-LD value object. [Confirmed: DataType, relates to rdf:langString.]",
	"ObjectReference": "**CDIF** A reference to another node by its @id, OR a structured PropertyValue. [Confirmed DataType shape: exactly two optional attributes.]",
	"PackageInformation": "",
	"PackageInformation": "",
	"PackageInformation": "",
	"PackageInformation": "",
	"PackageInformation": "",
	"PackageInformation": "",
	"PackageInformation": "",
	"PackageInformation": "",
	"PackageInformation": "",
	"PackageInformation": "",
	"PackageInformation": "",
	"TimePosition": "**CDIF** *(not documented)*",
	"XsdAnyUri": "**CDIF** XML Schema primitive datatype (XsdAnyUri).",
	"XsdDate": "**CDIF** XML Schema primitive datatype (XsdDate).",
	"XsdDateTime": "**CDIF** XML Schema primitive datatype (XsdDateTime).",
	"XsdLanguage": "**CDIF** XML Schema primitive datatype (XsdLanguage).",
	"tooltip.aggregation-kind": "",
	"tooltip.association": "",
	"tooltip.attribute": "",
	"tooltip.canonical-xmi": "",
	"tooltip.class": "",
	"tooltip.classifier": "",
	"tooltip.coupling": "",
	"tooltip.data-type": "",
	"tooltip.diagram": "",
	"tooltip.enumeration": "",
	"tooltip.encoding": "",
	"tooltip.enumeration-literal": "",
	"tooltip.inheritance": "",
	"tooltip.json-schema": "",
	"tooltip.json-ld": "",
	"tooltip.multiplicity": "",
	"tooltip.navigability": "",
	"tooltip.rdf-ontology": "",
	"tooltip.shacl": "",
	"tooltip.shex": "",
	"tooltip.usage": "",
	"tooltip.xml-schema": "",
}
