var modelUrl = 'https://w3id.org/cdif/discovery/1.1/xmi/';
var modelDocumentationUrl = '';
var definition = {
	"CDIFDiscovery": "Discovery extension properties for a CDIF Dataset.",
	"Classes": "Target classes of the CDIF profile.",
	"AbstractGeometry": "Abstract supertype of GeoCoordinates and GeoShape - the union-type collapse target for schema:geo on a SpatialExtent. The JSON anyOf admits either subtype.",
	"CatalogRecord": "Stub of CDIFCore::CatalogRecord. For the discovery profile, dcterms:conformsTo MUST include https://w3id.org/cdif/discovery/1.1.",
	"Dataset": "Stub of schema:Dataset (full definition in CDIFCore). The discovery profile adds measurementTechnique / variableMeasured / spatialCoverage / temporalCoverage / hasQualityMeasurement to this Dataset.",
	"DefinedTerm": "Stub of CDIFCore::DefinedTerm - a schema.org DefinedTerm typically backed by a SKOS Concept. Used as the controlled-vocabulary alternative to plain strings on measurementTechnique etc.",
	"GeoCoordinates": "schema:GeoCoordinates - point geometry with latitude / longitude.",
	"GeoShape": "schema:GeoShape - shape geometry (box, line, polygon, circle).",
	"Geometry": "geosparql:Geometry - structured spatial geometry serialized as Well-Known Text (geosparql:asWKT) with an optional coordinate reference system (geosparql:crs). Modelled as a real class (intentional exception to the union-shorthand: the BB defines real structure here).",
	"Instant": "OWL-Time time:Instant - a structured time point. Used as the value of time:hasBeginning / time:hasEnd on a TemporalExtent. Modelled as a real class because the BB defines real structure (an inTimePosition -> TimePosition reference).",
	"QualityMeasure": "A W3C DQV (Data Quality Vocabulary) quality metric definition - identifies the quality property being measured.",
	"QualityMeasurement": "A W3C DQV quality measurement: a measured value for a defined quality metric. References the metric (dqv:isMeasurementOf -> QualityMeasure) and carries the measured value (dqv:value).",
	"SpatialExtent": "Geographic extent of the resource content (schema:Place). Carries a place name, optional identifier, and optional geometry (geosparql:hasGeometry / schema:geo).",
	"TemporalExtent": "Temporal extent of resource content - the period of time the resource covers. Endpoints can be plain XSD dates OR OWL-Time Instants (time:hasBeginning / time:hasEnd) for structured time positions.",
	"TimePosition": "OWL-Time time:TimePosition - a numeric position on a temporal reference system. Carried by an Instant via time:inTimePosition.",
	"VariableMeasured": "A measured variable described as a schema:PropertyValue. Lightweight discovery-level shape: name, description, optional measurement technique, optional value range (min/maxValue) and unit (unitCode/unitText). Richer per-variable structure is added by cdifDataDescription.",
	"ModelIdentification": "Identification metadata for this profile model: constant, read-only attributes carrying the model's prefix, version, title, language and URI.",
	"XsdAnyUri": "Primitive data type \"anyURI\" of the XML Schema data types. represents a Uniform Resource Identifier Reference (URI). An \"anyURI\" value can be absolute or relative, and may have an optional fragment identifier (i.e., it may be a URI Reference). This type should be used to specify the intention that t ...",
	"XsdDate": "Primitive data type \"date\" of the XML Schema data types. For details see https://www.w3.org/TR/xmlschema-2/#date.",
	"tooltip.aggregation-kind": "",
	"tooltip.association": "",
	"tooltip.attribute": "",
	"tooltip.canonical-xmi": "",
	"tooltip.class": "",
	"tooltip.classifier": "",
	"tooltip.coupling": "",
	"tooltip.data-type": "",
	"tooltip.diagram": "",
	"tooltip.enumeration": "",
	"tooltip.encoding": "",
	"tooltip.enumeration-literal": "",
	"tooltip.inheritance": "",
	"tooltip.json-schema": "",
	"tooltip.json-ld": "",
	"tooltip.multiplicity": "",
	"tooltip.navigability": "",
	"tooltip.rdf-ontology": "",
	"tooltip.shacl": "",
	"tooltip.shex": "",
	"tooltip.usage": "",
	"tooltip.xml-schema": "",
}
