var modelUrl = 'https://w3id.org/cdif/core/1.0/xmi/';
var modelDocumentationUrl = '';
var definition = {
	"CDIFCore": "Core schema.org-aligned metadata for FAIR resource description.",
	"Classes": "Target classes of the CDIF profile.",
	"AbstractDistribution": "Abstract supertype for resource distributions (DataDownload for files, WebAPI for service endpoints). Use the concrete subclass that matches the access method.",
	"Action": "schema:Action - an operation invocable via a WebAPI (schema:Action or a subtype such as SearchAction, FindAction, AssessAction, ...).",
	"ActionResult": "Action result - the expected representation of an Action response (schema:DataDownload): encoding format and conformance, but no contentUrl/contentSize (generated per request). From the actionResult building block.",
	"AdditionalProperty": "schema:PropertyValue in the AdditionalProperty role - a key/value extension property carrying a propertyID (property name) and a value, optionally with a unit. Used wherever schema:additionalProperty appears. See CDIFDiscoveryImplementationGuide.md (Polymorphism of PropertyValue) for the distinction ...",
	"Agent": "Abstract supertype for actors that can play roles on a dataset (creator, publisher, contributor, funder). Use Person or Organization as the concrete realisation.",
	"CatalogRecord": "schema:subjectOf target - the metadata-record-about-the-metadata. Carries dcterms:conformsTo (with @id constant https://w3id.org/cdif/core/1.0 in this profile), dateCreated, dateModified, identifier.",
	"ContactPoint": "schema:ContactPoint - a contact point for an agent. The CDIF profile restricts this to email only.",
	"Contributor": "schema:Role / Contributor pattern. Pairs a Person or Organization (the contributor) with a roleName (e.g. principalInvestigator, curator, dataCollector).",
	"DataDownload": "schema:DataDownload - a downloadable file distribution of a Dataset. Inherits identifier/name/description from AbstractDistribution.",
	"Dataset": "schema:Dataset - the resource being described. Acts as the root of a CDIF metadata document.",
	"DefinedTerm": "schema:DefinedTerm - a term from a controlled vocabulary used as a value (keywords, additionalType, measurementTechnique, ...).",
	"DerivedFrom": "prov:wasDerivedFrom payload - a cdif:Reference to an upstream resource the dataset was derived from (the JSON also admits a bare string or @id). Mirrors the cdifDataType/cdifReference building block.",
	"EntryPoint": "schema:EntryPoint - documents the URL endpoint and request syntax used to invoke an Action.",
	"MonetaryGrant": "schema:MonetaryGrant - a funding award supporting the creation of the resource.",
	"Organization": "schema:Organization - an organisational agent. Inherits identifier and name from Agent.",
	"Person": "schema:Person - a human agent (creator, contributor, publisher, etc.). Inherits identifier and name from Agent.",
	"PropertyValueSpecification": "schema:PropertyValueSpecification - an explanation of a parameter used in the target URL template of an Action.",
	"ProvActivity": "prov:Activity - the activity that generated this resource (object of prov:wasGeneratedBy). Per the provProperties/generatedBy building block used by Core, modelled with only prov:used.",
	"WebAPI": "schema:WebAPI - an API distribution endpoint. Used as an alternative to schema:DataDownload for service-mediated access. Inherits identifier/name/description from AbstractDistribution.",
	"CdifConceptOrTerm": "Union shorthand for 'a concept reference (skos:Concept) OR a defined term (schema:DefinedTerm)'. In JSON instances the value MAY be: (a) an inline object typed as Concept / DefinedTerm, (b) an @id-only object referencing one, or (c) a plain string interpreted as the @id / prefLabel / termCode of the ...",
	"Identifier": "schema:PropertyValue used as schema:identifier - a structured identifier with type, value, and URL.",
	"ModelIdentification": "Identification metadata for this profile model: constant, read-only attributes carrying the model's prefix, version, title, language and URI.",
	"Reference": "A typed reference to an external entity (cdif:Reference). Provides a labeled link surface (name, description, url) plus the DDI-CDI dt-Reference semantics (uri, optional cdif:semantic describing the role). See the cdifDataType/cdifReference building block for the full definition; this is the per-pro ...",
	"XsdAnyUri": "Primitive data type \"anyURI\" of the XML Schema data types. represents a Uniform Resource Identifier Reference (URI). An \"anyURI\" value can be absolute or relative, and may have an optional fragment identifier (i.e., it may be a URI Reference). This type should be used to specify the intention that t ...",
	"XsdDate": "Primitive data type \"date\" of the XML Schema data types. For details see https://www.w3.org/TR/xmlschema-2/#date.",
	"XsdLanguage": "Derived data type \"language\" of the XML Schema data types. represents natural language identifiers as defined by by [RFC 3066]. The value space of \"language\" is the set of all strings that are valid language identifiers as defined [RFC 3066] . The lexical space of language is the set of all strings ...",
	"tooltip.aggregation-kind": "A shared aggregation is a variant of the association relationship; aggregation is more specific than association. It is an association that represents a part-whole or part-of relationship. The composite aggregation relationship is a stronger form of aggregation where the aggregate controls the lifecycle of the elements it aggregates.",
	"tooltip.association": "An association is a relationship between classes which is used to show that instances of classes could be linked to each other.",
	"tooltip.attribute": "Attributes (of a class or data type) hold data that is relevant to the entire class, not just a single object. For example, in a Car class, the number of wheels (assuming all cars have the same number) could be a class attribute.",
	"tooltip.canonical-xmi": "Canonical XMI constitutes a specific constrained format of XMI that supports interoperability between UML tools.",
	"tooltip.class": "A class classifies a set of objects and specifies the features that characterize the structure and behavior of those objects.",
	"tooltip.classifier": "Class or data type. ",
	"tooltip.coupling": "Coupling is the degree of interdependence between packages.",
	"tooltip.data-type": "Data types represent value types from primitive types like string or structured data types (other data types).",
	"tooltip.diagram": "A UML class diagram visually represents the structure of the class, including its attributes and their data types, as well as its relationships to other classes. ",
	"tooltip.enumeration": "An enumeration is a data type whose values are enumerated as defined enumeration literals.",
	"tooltip.encoding": "A target language refers to the programming language or platform for which the UML model is intended to be used to generate code.",
	"tooltip.enumeration-literal": "Enumeration literals are elements that represent named values in an enumeration.",
	"tooltip.inheritance": "The generalization relationship - also known as the inheritance relationship - captures the idea of one class, the so-called subclass, being a specialized form of the other (the superclass, super type, or base class). Where this relationship holds, the superclass is considered a generalization of the subclass. ",
	"tooltip.json-schema": "JSON Schema is the vocabulary that enables JSON data consistency, validity, and interoperability at scale.",
	"tooltip.json-ld": "JSON-LD is a method of encoding linked data using JSON and of serializing data similarly to traditional JSON.",
	"tooltip.multiplicity": "Multiplicity is a definition of cardinality - i.e. number of elements - of some collection of elements by providing an inclusive interval of non-negative integers to specify the allowable number of instances of described element. Multiplicity interval has some lower bound and (possibly infinite) upper bound.",
	"tooltip.navigability": "An end property of association is navigable from the opposite end(s) of association if instances of the classifier at this end of the link can be accessed efficiently at runtime from instances at the other ends of the link. The UML specification does not dictate how efficient this access should be or any specific mechanism to achieve the efficiency. It is implementation specific.",
	"tooltip.rdf-ontology": "RDF ontology is a formal representation of knowledge using the Resource Description Framework (RDF) that describes the concepts, relationships, and properties.",
	"tooltip.shacl": "Shapes Constraint Language (SHACL) is a language for describing Resource Description Framework (RDF) graphs. SHACL has been designed to enhance the semantic and technical interoperability layers of ontologies expressed as RDF graphs.",
	"tooltip.shex": "Shape Expressions (ShEx) is a data modelling language for validating and describing a Resource Description Framework (RDF).",
	"tooltip.usage": "Usage by a class or data type.",
	"tooltip.xml-schema": "XML Schema Definition specifies how to formally describe the elements in an Extensible Markup Language (XML) document.",
}
